"""Alembic 리비전이 모델과 일치하는지, 기동 시 리비전 확인이 동작하는지 고정한다.

여기서 막고 싶은 사고는 두 가지다.
1. 리비전을 안 만들고 모델만 고쳐서 배포 → DB 에 컬럼이 없어 런타임에 터진다.
2. 스키마가 어긋난 DB 로 앱이 조용히 뜬다 → 어긋난 채로 데이터가 쌓인다.
"""

import pytest
from alembic import command
from sqlalchemy import create_engine, inspect
from sqlalchemy.ext.asyncio import create_async_engine

from app import database
from app.database import Base

import app.models as _all_models  # noqa: F401  — Base.metadata 에 전체 테이블 등록


# Alembic 도입(T-B01) 전까지 `database._DEV_COLUMNS` 가 기동 때마다 ALTER TABLE 로 붙이던
# 컬럼 26개. baseline 리비전이 이걸 전부 포함해야 기존 DB 와 스키마가 같아진다.
# 목록은 제거된 코드에서 그대로 옮겼다 — 여기가 유일한 기록이므로 줄이지 말 것.
_LEGACY_DEV_COLUMNS: list[tuple[str, str]] = [
    ("users", "nickname"),
    ("users", "photo_url"),
    ("users", "bio"),
    ("users", "height_cm"),
    ("users", "mbti"),
    ("users", "job"),
    ("users", "region"),
    ("users", "smoking"),
    ("users", "drinking"),
    ("users", "religion"),
    ("users", "birth_place"),
    ("messages", "media_url"),
    ("messages", "media_type"),
    ("chat_threads", "user_a_last_read_id"),
    ("chat_threads", "user_b_last_read_id"),
    ("chat_threads", "user_a_left"),
    ("chat_threads", "user_b_left"),
    ("users", "chat_suspended_until"),
    ("user_photos", "is_face_verified"),
    ("users", "star_balance"),
    ("users", "pref_age_min"),
    ("users", "pref_age_max"),
    ("users", "pref_region"),
    ("users", "pref_height_min"),
    ("users", "username"),
    ("users", "password_hash"),
]


def _upgrade_head(url: str) -> None:
    cfg = database._alembic_config()
    cfg.set_main_option("sqlalchemy.url", url)
    command.upgrade(cfg, "head")


@pytest.fixture
def migrated_db(tmp_path):
    """`alembic upgrade head` 를 적용한 빈 SQLite 파일 DB 의 URL 을 준다.

    동기 픽스처인 게 중요하다 — alembic env.py 가 asyncio.run() 을 쓰므로
    이미 돌고 있는 이벤트 루프 안에서 부르면 깨진다.
    """
    db_file = tmp_path / "migrated.db"
    url = f"sqlite+aiosqlite:///{db_file}"
    _upgrade_head(url)
    return url, db_file


def test_upgrade_head_creates_model_schema(migrated_db):
    """리비전을 빈 DB 에 적용하면 모델과 같은 테이블·컬럼이 나온다."""
    _, db_file = migrated_db
    engine = create_engine(f"sqlite:///{db_file}")
    try:
        inspector = inspect(engine)
        actual_tables = set(inspector.get_table_names()) - {"alembic_version"}
        assert actual_tables == set(Base.metadata.tables)

        for name, table in Base.metadata.tables.items():
            actual = {c["name"]: c for c in inspector.get_columns(name)}
            assert set(actual) == set(table.columns.keys()), f"{name} 컬럼 불일치"
            for col in table.columns:
                assert actual[col.name]["nullable"] == col.nullable, (
                    f"{name}.{col.name} nullable 불일치"
                )
    finally:
        engine.dispose()


def test_no_drift_between_head_and_models(migrated_db):
    """`alembic check` 드리프트 0 — 모델을 고치고 리비전을 안 만들면 여기서 걸린다."""
    url, _ = migrated_db
    cfg = database._alembic_config()
    cfg.set_main_option("sqlalchemy.url", url)
    command.check(cfg)  # 차이가 있으면 AutogenerateDiffsDetected 로 실패한다


def test_baseline_contains_all_dev_columns(migrated_db):
    """제거한 _DEV_COLUMNS 26개가 baseline 에 전부 반영됐는지 대조한다."""
    _, db_file = migrated_db
    engine = create_engine(f"sqlite:///{db_file}")
    try:
        inspector = inspect(engine)
        missing = [
            f"{table}.{column}"
            for table, column in _LEGACY_DEV_COLUMNS
            if column not in {c["name"] for c in inspector.get_columns(table)}
        ]
        assert not missing, f"baseline 에 빠진 컬럼: {missing}"
    finally:
        engine.dispose()

    assert len(_LEGACY_DEV_COLUMNS) == 26


async def test_init_db_fails_on_unmigrated_db(monkeypatch, tmp_path):
    """리비전이 안 찍힌 DB 로는 기동하지 않고, 스키마를 만들지도 않는다."""
    db_file = tmp_path / "empty.db"
    engine = create_async_engine(f"sqlite+aiosqlite:///{db_file}")
    monkeypatch.setattr(database, "engine", engine)
    try:
        with pytest.raises(RuntimeError) as exc:
            await database.init_db()
    finally:
        await engine.dispose()

    message = str(exc.value)
    assert "alembic upgrade head" in message
    assert "alembic stamp head" in message

    sync_engine = create_engine(f"sqlite:///{db_file}")
    try:
        assert inspect(sync_engine).get_table_names() == []
    finally:
        sync_engine.dispose()


async def test_init_db_passes_on_migrated_db(monkeypatch, migrated_db):
    url, _ = migrated_db
    engine = create_async_engine(url)
    monkeypatch.setattr(database, "engine", engine)
    try:
        await database.init_db()
    finally:
        await engine.dispose()
